name: update wallper daily
run-name: ${{github.actor}} update wallper
on:
  schedule:
    - cron: "6 4 * * *"

jobs:
  fetchAndWrite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.GIT_ACTION_TOKEN}}
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: install
        run: npm install
      - name: build&write
        run: npm start
      - name: Commit and push
        run: |
          git config --global user.name 'tonysoul'
          git config --global user.email 'tonysoul@foxmail.com'
          git add picture/*
          git add wallper.json
          git add README.md
          git commit -am "update README"
          git push
